### ISSUE TITLE
Download Icon...ah, god

### ISSUE THREAD

**Issue by electrolom42** [fornit1917/music-download-plugin#3]
It's safe? 🤨

Why don't you use this icon (I made it myself):
![audio_row_dl](https://user-images.githubusercontent.com/25820887/50219638-7439e200-03c2-11e9-86f1-9af935dc9ed1.png)

It will be closer to the interface!
`Thank!`

**Comment by fornit1917** [comment]
It looks nice. I'll update the icon in the near future.

P.S.: да)
